<a href="https://colab.research.google.com/github/areeb-h-qureshi/Jovian/blob/main/Data%20Analysis%20with%20Python%3A%20Zero%20to%20Pandas/100_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the initialize.py module, then for each question you can query the answer or an hint with hint(n) or answer(n) for n question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)



In [2]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
np.array([0, 1, 2, 3]).nbytes

32

In [5]:
np.array([0, 1, 2, 3]).size * np.array([0, 1, 2, 3]).itemsize

32

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(10)
arr[4] = 1

In [9]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3,3)

array([[[0.5054142 , 0.31687044, 0.68579782],
        [0.87624651, 0.88903492, 0.30089322],
        [0.92155952, 0.25819134, 0.76995721]],

       [[0.95863468, 0.13014837, 0.32011026],
        [0.4304173 , 0.08799047, 0.69527491],
        [0.07563861, 0.14534116, 0.54264094]],

       [[0.56768599, 0.72712851, 0.544374  ],
        [0.51477417, 0.25070348, 0.54012639],
        [0.73865875, 0.78851206, 0.63380653]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
rand_arr = np.random.rand(10,10)
rand_arr.shape

(10, 10)

In [18]:
np.max(rand_arr)

0.9942822208439069

In [19]:
np.min(rand_arr)

0.01584786585528486

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
np.mean(np.random.rand(30))

0.5354174477058032

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
arr = np.ones([4,4])
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr2 = np.zeros([4,4])
arr2[0, :], arr2[-1, :] = 1, 1
arr2[:, 0], arr2[:, -1] = 1, 1
arr2

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [23]:
arr = np.eye(2)
arr2 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr2

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
0 * np.nan                  # nan
np.nan == np.nan            # False
np.inf > np.nan             # False
np.nan - np.nan             # nan
np.nan in set([np.nan])     # True
0.3 == 3 * 0.1              # False

False

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [26]:
temp = np.eye(4) * np.array([1,2,3,4])
res = np.zeros([5,5])
res[1:,0:-1] = temp
res

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
a = np.full((8,8), 'O', dtype='str')
a[::2, 1::2] = 'X'
a[1::2, ::2] = 'X'
print(a)

[['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
first = np.array(['O', 'X'])
second = np.array(['X', 'O'])
result =  np.tile([first,second], (4,4))
print(result)


[['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']
 ['O' 'X' 'O' 'X' 'O' 'X' 'O' 'X']
 ['X' 'O' 'X' 'O' 'X' 'O' 'X' 'O']]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [30]:
np.random.seed(2023)
arr = np.random.randint(1,56, size=(5,5)).astype('float64')
print(f'Array is:\n{arr}')
print(f'Sum of all elements is {np.round(np.sum(arr), 4)}')
print(f'Variance of all elements is {np.round(np.var(res), 4)}')

Array is:
[[24. 26.  7. 34. 29.]
 [ 4. 53. 53. 23. 38.]
 [33. 23. 18. 48. 54.]
 [48. 14. 40.  6. 25.]
 [51.  4. 29. 18. 47.]]
Sum of all elements is 749.0
Variance of all elements is 1.04


In [31]:
res = arr.copy()
res -= np.mean(res) 
res /= np.std(res)
print(f'Array is:\n{res}')
print(f'Sum of all elements is {np.round(np.sum(res), 4)}')
print(f'Variance of all elements is {np.round(np.var(res), 4)}')


Array is:
[[-0.37311381 -0.24790783 -1.43736461  0.25291607 -0.06009887]
 [-1.62517358  1.44237285  1.44237285 -0.4357168   0.50332803]
 [ 0.19031308 -0.4357168  -0.74873174  1.12935791  1.50497584]
 [ 1.12935791 -0.99914369  0.628534   -1.4999676  -0.31051082]
 [ 1.31716688 -1.62517358 -0.06009887 -0.74873174  1.06675492]]
Sum of all elements is -0.0
Variance of all elements is 1.0


> ## As Sum of all elements is zero(0) and variance is (1.0), we conclude that the data is now normalized.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [32]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
A = np.random.randint(1,56, size=(5, 3))
B = np.random.randint(1,56, size=(3, 2))

A @ B

array([[4367, 3975],
       [3582, 3875],
       [4637, 4556],
       [4697, 4657],
       [4853, 4747]])

In [34]:
np.dot(A, B)

array([[4367, 3975],
       [3582, 3875],
       [4637, 4556],
       [4697, 4657],
       [4853, 4747]])

In [35]:
np.matmul(A, B)

array([[4367, 3975],
       [3582, 3875],
       [4637, 4556],
       [4697, 4657],
       [4853, 4747]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [36]:
np.random.seed(2023)

arr = np.random.randint(1, 10, size=20)
print(f'Array: {arr}')
arr[(arr>3) & (arr<8)] *= -1
print(f'Negated Array: {arr}')



Array: [8 7 8 2 4 5 5 7 6 1 7 2 6 8 6 9 3 4 2 1]
Negated Array: [ 8 -7  8  2 -4 -5 -5 -7 -6  1 -7  2 -6  8 -6  9  3 -4  2  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
print(sum(range(5),-1)) # 9
from numpy import *
print(sum(range(5),-1)) # 10


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [38]:
Z = np.arange(10) # Initialize Unit Vector
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
try:
    Z**Z            # LEGAL : Element-wise exponentation i.e. 1**1 = 1, 2**2 = 2, 3**3 = 27. NOTE 0**0 = 1
    2 << Z >> 2     # LEGAL : Bitwise operations are performed from left to right
    Z <- Z          # LEGAL : Element wise negation is compared to orginal element. Boolean Array is returned
    1j*Z            # LEGAL : Element wise multiplication with unit imaginary number '0. + 1. j'
    Z/1/1           # LEGAL : Element wise division twice, executed left to right. dtype changes to float due to diviion operation
    Z<Z>Z           # ILLEGAL (VALUE ERROR): The truth value of an array with more than one element is ambiguous
except: 
    print('Error found!')

Error found!


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
print(np.array(0) / np.array(0))
print('****************************************')
print(np.array(0) // np.array(0))
print('****************************************')
print(np.array([np.nan]).astype(int).astype(float))

nan
****************************************
0
****************************************
[-9.22337204e+18]


<ipython-input-41-b9927aff92a4>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-41-b9927aff92a4>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)





In [42]:
arr = [-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0]
temp = np.ceil(np.abs(arr))
res = np.copysign(temp, arr)
res

array([-2., -2., -1.,  1.,  2.,  2.,  2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [43]:
arr1 = np.random.randint(-10, 10, size=12)
arr2 = np.random.randint(-10, 10, size=5)
np.intersect1d(arr1, arr2)


array([-2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [44]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [45]:
np.ones(1) / 0


array([inf])

In [46]:
np.seterr(divide="warn", over='warn', under='ignore', invalid='warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [47]:
np.ones(1) / 0

<ipython-input-47-29114bad1145>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.ones(1) / 0


array([inf])

In [52]:
with np.errstate(all="warn"):
    np.ones(1) / 0

<ipython-input-52-42748a9956c2>:2: RuntimeWarning: divide by zero encountered in true_divide
  np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.sqrt(-1)

<ipython-input-54-597592b72a04>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [55]:
np.emath.sqrt(-1)

1j

In [53]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-53-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [57]:
# Yesterday
np.datetime64('today') - np.timedelta64(1)

numpy.datetime64('2023-01-22')

In [58]:
# Today
np.datetime64('today')

numpy.datetime64('2023-01-23')

In [59]:
# Tomorrow
np.datetime64('today') + np.timedelta64(1)

numpy.datetime64('2023-01-24')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [62]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [96]:
A = np.arange(5).astype('float')
B = np.arange(6,11).astype('float')


np.add(A,B, out=B)

np.negative(A, out=A)

np.divide(A, 2, out=A)

np.multiply(A, B, out=A)

array([ -0.,  -4., -10., -18., -28.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [104]:
arr = np.random.uniform(0,10,10)
print(arr)
print(arr.astype(np.int64))
print(arr//1)
print(arr-(arr%1))
print(np.floor(arr))
print(np.trunc(arr))

[6.55048528 4.85440602 7.2683691  4.21614128 2.14963404 1.64886024
 6.49758442 9.84063368 0.27450767 1.69569041]
[6 4 7 4 2 1 6 9 0 1]
[6. 4. 7. 4. 2. 1. 6. 9. 0. 1.]
[6. 4. 7. 4. 2. 1. 6. 9. 0. 1.]
[6. 4. 7. 4. 2. 1. 6. 9. 0. 1.]
[6. 4. 7. 4. 2. 1. 6. 9. 0. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [106]:
np.tile(np.arange(5), 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [107]:
np.tile(np.arange(5).reshape(-1,1), 5)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)